
-- Auto-generated SQL DDL from SQLAlchemy models
-- Generated by scripts/generate_db_sql.py
-- DO NOT EDIT MANUALLY

CREATE TABLE customers (
	id SERIAL NOT NULL, 
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	name VARCHAR(255) NOT NULL, 
	email VARCHAR(255) NOT NULL, 
	phone VARCHAR(20), 
	status VARCHAR(50) NOT NULL, 
	PRIMARY KEY (id)
)

;

CREATE TABLE products (
	id SERIAL NOT NULL, 
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	name VARCHAR(255) NOT NULL, 
	description VARCHAR, 
	price NUMERIC NOT NULL, 
	cost NUMERIC, 
	stock_quantity INTEGER NOT NULL, 
	status VARCHAR(50) NOT NULL, 
	PRIMARY KEY (id)
)

;

CREATE TABLE orders (
	id SERIAL NOT NULL, 
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	customer_id INTEGER NOT NULL, 
	product_id INTEGER NOT NULL, 
	quantity INTEGER NOT NULL, 
	total_price NUMERIC NOT NULL, 
	cost NUMERIC, 
	status VARCHAR(50) NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(customer_id) REFERENCES customers (id), 
	FOREIGN KEY(product_id) REFERENCES products (id)
)

;
CREATE UNIQUE INDEX ix_customers_email ON customers (email);

