#!/usr/bin/env python
"""
Generate SQL DDL from SQLAlchemy models.

This script creates a PostgreSQL-compatible SQL file containing all table definitions,
constraints, indexes, and sequences needed to initialize the database.

Usage:
    python scripts/generate_db_sql.py
"""

import sys
from pathlib import Path

from sqlalchemy import text, MetaData
from sqlalchemy.schema import CreateTable, CreateIndex, CreateSequence
from sqlalchemy.dialects import postgresql

# Add project root to path
project_root = Path(__file__).parent.parent
sys.path.insert(0, str(project_root))

from leaf_api.app import create_app
from leaf_api.models import db


def generate_sql_ddl() -> str:
    """Generate complete DDL SQL for all tables, indexes, and sequences."""
    app = create_app("development")

    with app.app_context():
        metadata = db.metadata

        # Compile to PostgreSQL dialect
        dialect = postgresql.dialect()
        statements = []

        # Generate CREATE SEQUENCE statements for auto-increment IDs
        # SQLAlchemy handles sequences implicitly for PostgreSQL, but we can make them explicit
        for table in metadata.sorted_tables:
            # PostgreSQL SERIAL/BIGSERIAL creates implicit sequences
            # We'll let the CREATE TABLE statement handle it via SERIAL/BIGSERIAL
            pass

        # Generate CREATE TABLE statements
        for table in metadata.sorted_tables:
            create_table = CreateTable(table)
            compiled = create_table.compile(dialect=dialect)
            statements.append(f"{compiled};\n")

        # Generate CREATE INDEX statements for indexes not part of constraints
        for table in metadata.sorted_tables:
            for index in table.indexes:
                # Skip primary key indexes (created with table)
                if not index.unique or not all(col.primary_key for col in index.columns):
                    create_index = CreateIndex(index)
                    compiled = create_index.compile(dialect=dialect)
                    statements.append(f"{compiled};\n")

        return "".join(statements)


def main():
    """Generate and write SQL DDL to file."""
    # Add header comment

    print(f"""
-- Auto-generated SQL DDL from SQLAlchemy models
-- Generated by scripts/generate_db_sql.py
-- DO NOT EDIT MANUALLY
{generate_sql_ddl()}""")


if __name__ == "__main__":
    main()
